//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST465_Project.WebForms {
    
    
    public partial class ValidatedForm {
        
        /// <summary>
        /// uxName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_Project.WebForms.RequiredTextBox uxName;
        
        /// <summary>
        /// uxFavoriteColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_Project.WebForms.RequiredTextBox uxFavoriteColor;
        
        /// <summary>
        /// uxCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_Project.WebForms.RequiredTextBox uxCity;
        
        /// <summary>
        /// uxSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button uxSubmit;
    }
}
